// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MobilerningBackEnd.Repositories;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MobilearningBackEnd.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221031195819_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MobilerningBackEnd.Models.Activity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("avaliation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("conclusion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("imageURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("information")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("introduction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("process")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("references")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("subttitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("task")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("MobilerningBackEnd.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MobilerningBackEnd.Models.UserActivity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("activityid")
                        .HasColumnType("integer");

                    b.Property<string>("currentStage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("endDate")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("idActivity")
                        .HasColumnType("integer");

                    b.Property<int>("idUser")
                        .HasColumnType("integer");

                    b.Property<double?>("progress")
                        .IsRequired()
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("startDate")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("userId")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("activityid");

                    b.HasIndex("userId");

                    b.ToTable("UserActivities");
                });

            modelBuilder.Entity("MobilerningBackEnd.Models.Word", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("EnglishDefinition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EnglishWord")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PortugueseDefinition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PortugueseWord")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("MobilerningBackEnd.Models.UserActivity", b =>
                {
                    b.HasOne("MobilerningBackEnd.Models.Activity", "activity")
                        .WithMany()
                        .HasForeignKey("activityid");

                    b.HasOne("MobilerningBackEnd.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("userId");

                    b.Navigation("activity");

                    b.Navigation("user");
                });
#pragma warning restore 612, 618
        }
    }
}
