CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Activities" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    introduction text NOT NULL,
    task text NOT NULL,
    process text NOT NULL,
    information text[] NOT NULL,
    avaliation text NOT NULL,
    conslusion text NOT NULL,
    "references" text[] NOT NULL,
    title text NOT NULL,
    subttitle text NOT NULL,
    "imageURL" text NOT NULL,
    CONSTRAINT "PK_Activities" PRIMARY KEY (id)
);

CREATE TABLE "UserActivities" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    "currentStage" text NOT NULL,
    progress double precision NOT NULL,
    "startDate" timestamp with time zone NOT NULL,
    "endDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_UserActivities" PRIMARY KEY (id)
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Email" text NOT NULL,
    "Password" text NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "Words" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "PortugueseWord" text NOT NULL,
    "EnglishWord" text NOT NULL,
    "PortugueseDefinition" text NOT NULL,
    "EnglishDefinition" text NOT NULL,
    CONSTRAINT "PK_Words" PRIMARY KEY ("ID")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20221029144633_InitialCreate', '6.0.8');

COMMIT;

